### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: google/gemma-3-4b-pt
adapter_name_or_path: ../saves/gemma-4b/lora/sft_lmtp_stage2_0.02
template: gemma3
trust_remote_code: true

### export
export_dir: ../saves/gemma-4b/merged/sft_lmtp_stage2_0.02
export_size: 5
export_device: cpu
export_legacy_format: false
