### model
model_name_or_path: google/gemma-3-4b-pt
trust_remote_code: true
mtp_type: lmtp1
num_heads: 3
stage1_pretrained_path: /home/storage/LMTP/saves/gemma_4b/full/sft_lmtp_stage1

### method
stage: sft
do_train: true
finetuning_type: full
pure_bf16: true # important for full parameter fine-tuning, if false, it will use fp32 ! if deepspeed is used, do not set pure_bf16
deepspeed: ../configs/ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]


### dataset
dataset: mixed_G3_4b
template: gemma
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: ../saves/gemma_4b/full/sft_lmtp_stage1
logging_steps: 10
save_strategy: 'no'
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 64
learning_rate: 1.0e-3
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
